"""empty message

Revision ID: eeb9ea61aa83
Revises: 
Create Date: 2023-10-11 20:51:11.992868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eeb9ea61aa83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index('ix_addresses_user_id')

    op.drop_table('addresses')
    op.drop_table('teacher')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('groups')
    op.drop_table('class')
    op.drop_table('student')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index('uix_id_name')

    op.drop_table('person')
    with op.batch_alter_table('prefrences', schema=None) as batch_op:
        batch_op.drop_index('ix_prefrences_user_id')

    op.drop_table('prefrences')
    op.drop_table('users_roles')
    op.drop_table('sc')
    op.drop_table('servers_to_sys_users')
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index('hostname')

    op.drop_table('servers')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('slug')

    op.drop_table('roles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('users')
    with op.batch_alter_table('sys_users', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('sys_users')
    op.drop_table('course')
    op.drop_table('department')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_numeric_field', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('new_numeric_field')

    op.create_table('department',
    sa.Column('DepartmentID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ParentID', mysql.INTEGER(), autoincrement=False, nullable=True, comment='parent id'),
    sa.Column('DepartmentName', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('DepartmentID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('course',
    sa.Column('CourseID', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=False, comment='课号'),
    sa.Column('CourseName', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=False, comment='课程名'),
    sa.Column('Hours', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=False, comment='学时'),
    sa.Column('Credit', mysql.FLOAT(), nullable=True, comment='学分'),
    sa.Column('TeacherID', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=15), nullable=True, comment='教师编号'),
    sa.Column('StudentCount', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学生选课人数'),
    sa.PrimaryKeyConstraint('CourseID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('password', sa.VARBINARY(length=1137), nullable=True),
    sa.Column('key', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sys_users', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=False)

    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('slug', ['slug'], unique=False)

    op.create_table('servers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hostname', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index('hostname', ['hostname'], unique=False)

    op.create_table('servers_to_sys_users',
    sa.Column('nid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('server_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['sys_users.id'], name='servers_to_sys_users_ibfk_2'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name='servers_to_sys_users_ibfk_1'),
    sa.PrimaryKeyConstraint('nid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sc',
    sa.Column('StudentID', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=False, comment='学号'),
    sa.Column('CourseID', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=False, comment='课号'),
    sa.Column('Score', mysql.INTEGER(), autoincrement=False, nullable=True, comment='成绩'),
    sa.Column('Regtime', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('StudentID', 'CourseID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users_roles',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='users_roles_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_roles_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prefrences',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('language', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='prefrences_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('prefrences', schema=None) as batch_op:
        batch_op.create_index('ix_prefrences_user_id', ['user_id'], unique=False)

    op.create_table('person',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index('uix_id_name', ['id', 'name'], unique=False)

    op.create_table('student',
    sa.Column('StudentID', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=False, comment='学号'),
    sa.Column('Name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=False, comment='姓名'),
    sa.Column('Sex', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), nullable=False, comment='性别'),
    sa.Column('EnrollmentTime', mysql.DATETIME(), nullable=True, comment='入学时间'),
    sa.Column('DepartmentID', mysql.INTEGER(), autoincrement=False, nullable=True, comment='所在院系'),
    sa.Column('ClassID', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=20), nullable=True, comment='所在班级'),
    sa.Column('Address', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='家庭住址'),
    sa.Column('AddTime', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('StudentID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('class',
    sa.Column('ClassID', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=20), nullable=False),
    sa.Column('ClassName', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=20), nullable=True),
    sa.PrimaryKeyConstraint('ClassID'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('groups',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('cn_name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('teacher',
    sa.Column('TeacherID', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=15), nullable=False, comment='教师编号'),
    sa.Column('TeacherName', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=False, comment='教师名'),
    sa.Column('DepartmentID', mysql.INTEGER(), autoincrement=False, nullable=False, comment='所属院系'),
    sa.Column('Salary', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=True, comment='工资'),
    sa.Column('Mobile', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=15), nullable=True, comment='教师手机号'),
    sa.PrimaryKeyConstraint('TeacherID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('addresses',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('road_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('postcode', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='addresses_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index('ix_addresses_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
